### ISSUE TITLE
Two viewers next to each other

### ISSUE THREAD

**Issue by dackom** [ImagingDataCommons/dicom-microscopy-viewer#151]
Hello.

I need to create an app that will have two viewers next to each other in the same page. The idea is to compare two microscopy images, and when you drag/move one or zoom, the other one should also be moved/zoomed.

I started by looking for the events that viewer is publishing, and I see that there are dicommicroscopyviewer_move_started and dicommicroscopyviewer_move_ended events, but they are never fired.

Do you have any ideas how this can be done?

**Comment by igoroctaviano** [comment]
Addressed by https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/155
