### ISSUE TITLE
Request: Target IE 11

### ISSUE THREAD

**Issue by dannyrb** [ImagingDataCommons/dicom-microscopy-viewer#35]
All of the other `dcmjs-org` libraries appear to transpile/target `IE 11` using `babel`. I believe, consumers of `dicom-microscopy-viewer` that target `IE 11` will need to transpile this dependency on every build unless an IE 11 build is provided.

Please consider adopting the same approach used in the other repositories to make this package easier to add as a dependency 🙏 

https://github.com/dcmjs-org/dcmjs/blob/master/.babelrc

**Comment by pieper** [comment]
Whatever you say!

Maybe you can make a PR?  Is it just a matter of adding the one file?

**Comment by igoroctaviano** [comment]
Addressed by #156
