### ISSUE TITLE
Assert code 17 - resolutions_ assertion

### ISSUE THREAD

**Issue by jamesdigid** [ImagingDataCommons/dicom-microscopy-viewer#81]
I am using OHIF as a viewer which is erroring out on this assertion when attempting to view WSI studies:

```
    assert(isSorted(this.resolutions_, function(a, b) {
      return b - a;
    }, true), 17);
```

I'm unclear on the purpose of this, or why it might be failing. Any insights would be much appreciated.

Thanks

**Comment by hackermd** [comment]
Thanks for reporting the issue @jamesdigid. Could you kindly provide some additional information (version of the software, data used, etc.) that may help us debug the problem.

**Comment by hackermd** [comment]
Could you try whether you can reproduce the problem using Slim (https://github.com/herrmannlab/slim)?
