### ISSUE TITLE
Add dicom-microscopy-viewer to OHIF

### ISSUE THREAD

**Issue by rferreiroa** [ImagingDataCommons/dicom-microscopy-viewer#86]
I have some questions. Is it possible to add this lib to OHIF? 

I tested OHIF and i loaded images in a Orthanc Server and visualized with OHIF but there is not annotation tools for example.

Someone can explain the difference betwwen this dicom-microscopy-viewer and the other one that is in OHIF?

On the other hand. Can someone explain where i can modify and develop over OpenLayers. I saw that OpenLayers is installed to render WSI images.

Kind regards.

**Comment by hackermd** [comment]
@selko thanks for your interest in contributing to Slim.

>  Is it possible to add this lib to OHIF?
> I tested OHIF and i loaded images in a Orthanc Server and visualized with OHIF but there is not annotation tools for example.
> Someone can explain the difference betwwen this dicom-microscopy-viewer and the other one that is in OHIF?

The microscopy extension of the OHIF viewer is just thin wrapper around the *dicom-microscopy-viewer* library. However, the OHIF viewer only exposes part of the [dicom-microscopy-viewer API](https://imagingdatacommons.github.io/dicom-microscopy-viewer/) and only provides basic viewing functionality.

For the NCI Imaging Data Commons, we decided to use the [Slim](https://github.com/ImagingDataCommons/slim/) viewer for display and annotation of slide microscopy images and we implemented annotation tools in Slim (see our [paper](https://arxiv.org/abs/2205.09122) for further information).

The Slim and OHIF viewers are conceptually similar, share many libraries under the hood (e.g., [dicomweb-client](https://github.com/dcmjs-org/dicomweb-client)), have inspired each other over the last years, and are developed jointly by members of the IDC team.

> Can someone explain where i can modify and develop over OpenLayers. I saw that OpenLayers is installed to render WSI images.

I suggest taking a look at the implementation of the [VolumeImageViewer](https://imagingdatacommons.github.io/dicom-microscopy-viewer/viewer.VolumeImageViewer.html), which demonstrates how methods internally use and abstract the underlying Openlayers API. The [VolumeImageViewer.activateDrawInteraction()](https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/73c803806897a7c693bee66d5f38e5500890beea/src/viewer.js#L2151-L2289) method may be a good starting point.

Before getting started, please also review the [contribution guidelines](https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/master/CONTRIBUTING.md).

**Comment by hackermd** [comment]
@selko we would welcome your contribution. Please don't hesitate to reach out if you have further questions or if you would like to discuss design considerations or implementation details.

**Comment by selko** [comment]
Thank you for your response and attention. I am going to test all that you explained. I will come back soon when i go deeper testing all stuff.

kind regards!

**Comment by igoroctaviano** [comment]
> Thank you for your response and attention. I am going to test all that you explained. I will come back soon when i go deeper testing all stuff.
> 
> kind regards!

Closing this ticket for now. @rferreiroa please new issues if needed.
