### ISSUE TITLE
Revisit status checks for branch configuration

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/dicom-microscopy-viewer#89]
@hackermd we removed status checks to work around presumed blocking issue, since you renamed the task in github actions workflow, but we cannot figure out how to add new status checks that have the updated name. Maybe you can help with this? Related to #85.

**Comment by hackermd** [comment]
Are you referring to status checks or to deployments that must succeed? I just looked into the repository settings, and it appears that the actions are not found.

**Comment by hackermd** [comment]
I noticed the following message: `Sorry, we couldn’t find any status checks in the last week for this repository`.

I then triggered the actions by committing to the protected branch. Afterwards, the status checks were found. Weird behavior..
