### ISSUE TITLE
Microscopy images (modality = SM) doesn't render on the viewer.

### ISSUE THREAD

**Issue by md-prog** [ImagingDataCommons/dicom-microscopy-viewer#94]
Similar to the issue #31 , but different reason.

The reason is: `FrameOfReferenceUID` of each layer of the image pyramid is often different ( usually not totally different but with some matches, for example, `2.16.840.1.113883.3.8467.132979444839078229637890676839078229.10` and `2.16.840.1.113883.3.8467.132979444839078229637890676839078229.9`, only the last number `10` and `9` is different), when the DICOM is generated by aggregating the layer images.

I recognize if these numbers are different between layers, we would have problems when rendering annotations.
But on the condition that we are not using the annotations, it should at least render the image.

This is the line where it was blocked by throwing error:

https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/097282b5690886735f3fe6521d0774ee33b7f418/src/pyramid.js#L78

**Comment by hackermd** [comment]
The Frame of Reference UID must be identical between images. If the images were defined in a different [Frame of Reference](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/chapter_A.html#sect_A.1.2.5) (i.e., coordinate system), they would need to be registered to be visualized together in the same viewport.
